development:
  cloud_name: "dxleey3up"
  api_key: "235797814912753"
  api_secret: "c-YclQW39jqU5whxIs-OudXiqTY"
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: "dxleey3up"
  api_key: "235797814912753"
  api_secret: "c-YclQW39jqU5whxIs-OudXiqTY"
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: "dxleey3up"
  api_key: "235797814912753"
  api_secret: "c-YclQW39jqU5whxIs-OudXiqTY"
  enhance_image_tag: true
  static_image_support: false
